name: Build for Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v5.0.0

      - name: Install dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build
        run: "npm run build"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        if: ${{ !env.ACT }}
        with:
          path: .

  build-demos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v5.0.0

      - name: Install dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build
        run: "npm run build-demos"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        if: ${{ !env.ACT }}
        with:
          path: .

  deploy:
    needs: build-demos

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
